create table Person
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name    varchar(100)                                             NOT NULL,
    year_of_born int CHECK ( year_of_born > 1930 AND year_of_born < 2025) NOT NULL,
    password     varchar                                                  NOT NULL
);
INSERT INTO Person(user_name, year_of_born, password)
VALUES ('Пушкин Кирилл Алексеевич', 1997, 'gg1');

INSERT INTO Person(user_name, year_of_born, password)
VALUES ('Иванов Денис Геннадьевич', 1997, 'gg2');

ALTER TABLE Person
    ADD COLUMN created_at timestamp,
    ADD COLUMN update_at timestamp,
    ADD COLUMN created_who varchar;
