CREATE TABLE Person
(
    id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    age  int check ( age < 100 )
);

CREATE TABLE Passport
(
    id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    passport_number int NOT NULL,
    person_id       int UNIQUE REFERENCES person (id) ON DELETE CASCADE
);


CREATE TABLE Item
(
    id        int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id int          REFERENCES Person (id) ON DELETE SET NULL,
    item_name varchar(100) NOT NULL
);

INSERT INTO Person(name, age)
VALUES ('Sheremetivsky Maria', 23);
INSERT INTO Person(name, age)
VALUES ('Shumilova Elena', 22);
INSERT INTO Person(name, age)
VALUES ('Nazarov Alex', 23);

INSERT INTO Item(person_id, item_name)
VALUES (1, 'Book');
INSERT INTO Item(person_id, item_name)
VALUES (1, 'AirPods');
INSERT INTO Item(person_id, item_name)
VALUES (2, 'Iphone');
INSERT INTO Item(person_id, item_name)
VALUES (3, 'Kindle');
INSERT INTO Item(person_id, item_name)
VALUES (3, 'TV');
INSERT INTO Item(person_id, item_name)
VALUES (3, 'PlayStation');