CREATE TABLE Item
(
    id        int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id int          REFERENCES Person (id) ON DELETE SET NULL,
    item_name varchar(100) NOT NULL
);


INSERT INTO Item(person_id, item_name)
VALUES (1, 'Book');
INSERT INTO Item(person_id, item_name)
VALUES (1, 'AirPods');
INSERT INTO Item(person_id, item_name)
VALUES (2, 'Iphone');
INSERT INTO Item(person_id, item_name)
VALUES (3, 'Kindle');
INSERT INTO Item(person_id, item_name)
VALUES (3, 'TV');
INSERT INTO Item(person_id, item_name)
VALUES (3, 'PlayStation');