create table People
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullName     varchar(100) NOT NULL UNIQUE,
    year_of_born int CHECK ( year_of_born > 1930 AND year_of_born < 2025)
);
INSERT INTO People(fullName, year_of_born)
VALUES ('Шумилова Елена Алексеевна', 2000);
INSERT INTO People(fullName, year_of_born)
VALUES ('Шереметьевская Мария Валерьевна', 2001);
INSERT INTO People(fullName, year_of_born)
VALUES ('Иванов Денис Геннадьевич', 1997);
INSERT INTO People(fullName, year_of_born)
VALUES ('Гальвас Михаил Андреевич', 2000);
INSERT INTO People(fullName, year_of_born)
VALUES ('Иванова Ольга Владимировна', 1977);
INSERT INTO People(fullName, year_of_born)
VALUES ('Кабанова Анна Николаевна', 2000);
INSERT INTO People(fullName, year_of_born)
VALUES ('Веселов Михаил Алексеевич', 1999);


create table Books
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        varchar(100) NOT NULL,
    author       varchar(100) NOT NULL,
    release_date int CHECK ( release_date > 0 AND release_date < 2025),
    person_id    int          REFERENCES People (id) ON DELETE SET NULL
);
INSERT INTO Books(title, author, release_date, person_id)
VALUES ('Думай', 'Стюарт МакРоберт', 1950, 3);
INSERT INTO Books(title, author, release_date, person_id)
VALUES ('Правильные роды', 'К.И.Чайковский', 2008, 5);
INSERT INTO Books(title, author, release_date, person_id)
VALUES ('Спорт', 'Арнольд Шварцнеггер', 1950, 2);

ALTER TABLE Books
    ADD COLUMN taking_book TIMESTAMP;



INSERT INTO Books(title, author, release_date)
VALUES ('День опричника', 'Владимир Сорокин', 2006);
INSERT INTO Books(title, author, release_date)
VALUES ('Философия Java', 'Брюс Эккель', 2018);
INSERT INTO Books(title, author, release_date)
VALUES ('Игра в бисер', 'Герман Гессе', 1943);
INSERT INTO Books(title, author, release_date)
VALUES ('Тайные виды на гору Фудзи', 'Владимир Пелевин', 2018);
INSERT INTO Books(title, author, release_date)
VALUES ('Бытие и время', 'Мартин Хайдеггер', 1927);

-------------------------------------------------------------------------------------

SELECT books.title, people.fullname, people.year_of_born
FROM books
         LEFT JOIN people on books.person_id = people.id;

-------------------------------------------------------------------------------------

create table Admins
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullName   varchar(100) NOT NULL UNIQUE,
    yearOfBorn int CHECK ( yearOfBorn > 1930 AND yearOfBorn < 2025),
    password   varchar
);
INSERT INTO Admins(fullName, yearOfBorn, password)
VALUES ('Иванов Иван Иванович', 2000, 'gg1');

create table Roles
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role varchar
);
INSERT INTO Roles(role)
VALUES ('ROLE_ADMIN');


CREATE TABLE Admins_Roles
(
    admin_id INT,
    role_id  INT,
    PRIMARY KEY (admin_id, role_id),
    FOREIGN KEY (admin_id) REFERENCES Admins (id) ON DELETE SET NULL,
    FOREIGN KEY (role_id) REFERENCES Roles (id) ON DELETE SET NULL
);


